columns:
  - id: timeline
    name: Timeline
    pattern: all

  - id: mention
    name: Mention
    pattern: mention

  - id: sample
    name: Sample
    pattern: "きらら OR ゆるゆり OR ごちうさ OR ご注文はうさぎですか OR きんモザ OR きんいろモザイク OR あわあわ"